swagger: "2.0"
info:
  description: "This is a product service documentation"
  version: "1.0.0"
  title: "Product service"
schemes:
- "https"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "List all products"
      description: ""
      operationId: "getProductsList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProductsById"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "string"
        format: "uuid"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Product not found"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      count:
        type: "integer"
        format: "int32"
      description:
        type: "string"
      title:
        type: "string"
      price:
        type: "number"
        format: "double"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"